{% set name = "mumps" %}
{% set version = "5.0.2" %}
{% set sha256 = "77292b204942640256097a3da482c2abcd1e0d5a74ecd1d4bab0f5ef6e60fe45" %}
{% set variant = "openblas" %}

package:
  name: mumps
  version: {{ version }}

source:
  fn: MUMPS_{{ version }}.tar.gz
  url: http://mumps.enseeiht.fr/MUMPS_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - mumps_mpi.patch
    - cmake.patch  # [win]
build:
  number: 210
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - cmake  # [win]
    - patch  # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas                  # [not win]
    - metis        # [not win]
    - scotch  # [not win]
    - m2w64-openblas  # [win]
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas                  # [not win]
    - metis  # [not win]
    - scotch  # [not win]
    - m2w64-openblas  # [win]

test:
  commands:
    - test -f "${PREFIX}/lib/libsmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libdmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libcmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libzmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libmumps_common.a"  # [not win]
    - test -f "${PREFIX}/lib/libpord.a"  # [not win]
    - test -f "${PREFIX}/include/dmumps_struc.h"  # [not win]
    - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libsmumps.dll" exit 1  # [win]
    - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libdmumps.dll" exit 1  # [win]
    - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libcmumps.dll" exit 1  # [win]
    - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libzmumps.dll" exit 1  # [win]
    - if not exist "%LIBRARY_PREFIX%\mingw-w64\lib\libmumps_common.a" exit 1  # [win]
    - if not exist "%LIBRARY_PREFIX%\mingw-w64\lib\libpord.a" exit 1  # [win]
    - if not exist "%LIBRARY_PREFIX%\mingw-w64\include\dmumps_struc.h" exit 1  # [win]
    - if not exist "%LIBRARY_PREFIX%\mingw-w64\include\mumps_mpi.h" exit 1  # [win]

about:
  home: http://mumps.enseeiht.fr/
  license: CeCILL-C
  license_file: LICENSE
  summary: 'MUMPS: a parallel sparse direct solver'
  description: |
    MUMPS (MUltifrontal Massively Parallel Solver) is a package for solving
    systems of linear equations of the form Ax = b, where A is a square sparse
    matrix that can be either unsymmetric, symmetric positive definite, or
    general symmetric, on distributed memory computers. MUMPS implements a
    direct method based on a multifrontal approach which performs a Gaussian
    factorization.
  doc_url: http://mumps.enseeiht.fr/index.php?page=doc

extra:
  recipe-maintainers:
    - basnijholt
    - minrk
