{% set name = "mumps" %}
{% set version = "5.0.2" %}
{% set sha256 = "77292b204942640256097a3da482c2abcd1e0d5a74ecd1d4bab0f5ef6e60fe45" %}
{% set variant = "openblas" %}

package:
  name: mumps
  version: {{ version }}

source:
#  fn: MUMPS_{{ version }}.tar.gz
  path: C:\\Users\rotis\git\MUMPS_5.0.2
#  sha256: {{ sha256 }}
  patches:
    - mumps_mpi.patch
build:
  number: 203
  features:
    - blas_{{ variant }} # [not win]

requirements:
  build:
    - toolchain # [not win]
    - blas 1.1 {{ variant }} # [not win]
    - openblas 0.2.19|0.2.19.* # [not win]
    - gcc # [not win]
    - m2w64-toolchain # [win]
    - m2w64-openblas # [win]
    - cmake # [win]
    - patch # [win]
  run:
    - blas 1.1 {{ variant }} # [not win]
    - openblas 0.2.19|0.2.19.* # [not win]
    - libgfortran # [not win]
    - m2w64-openblas # [win]

test:
  commands:
    - test -f "${PREFIX}/lib/libdmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libmumps_common.a"  # [not win]
    - test -f "${PREFIX}/lib/libpord.a"  # [not win]
    - test -f "${PREFIX}/include/dmumps_struc.h"  # [not win]
    - if not exist "%LIBRARY_LIB%\\libdmumps.dll" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libmumps_common.a" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libpord.a" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\dmumps_struc.h" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\mumps_mpi.h" exit 1  # [win]


about:
  home: http://mumps.enseeiht.fr/
  license: CeCILL-C
  license_file: LICENSE
  summary: 'MUMPS: a parallel sparse direct solver'
  description: |
    MUMPS (“MUltifrontal Massively Parallel Solver”) is a package for solving 
    systems of linear equations of the form Ax = b, where A is a square sparse 
    matrix that can be either unsymmetric, symmetric positive definite, or 
    general symmetric, on distributed memory computers. MUMPS implements a 
    direct method based on a multifrontal approach which performs a Gaussian 
    factorization.
  doc_url: http://mumps.enseeiht.fr/index.php?page=doc

extra:
  recipe-maintainers:
    - basnijholt
