{% set name = "mumps" %}
{% set version = "5.1.2" %}
{% set sha256 = "eb345cda145da9aea01b851d17e54e7eef08e16bfa148100ac1f7f046cd42ae9" %}
{% set variant = "openblas" %}

package:
  name: mumps
  version: {{ version }}

source:
  fn: MUMPS_{{ version }}.tar.gz
  url: http://mumps.enseeiht.fr/MUMPS_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002

requirements:
  build:
    # dummy unused top-level requirements
    # needed to construct the right conda-smithy matrix
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - mpi * {{ mpi }}  # [mpi != 'nompi']

outputs:
  {% if not win %}
  - name: mumps-include
    build:
      script: ${RECIPE_DIR}/build-headers.sh
    requirements:
      build: []
      host: []
    test:
      commands:
        - test -f "${PREFIX}/include/mumps_compat.h"
  {% endif %}

  {% if mpi == 'nompi' %}
  - name: mumps-seq
    build:
      script: ${RECIPE_DIR}/build-seq.sh  # [not win]
      script: "%RECIPE_DIR%\\bld-seq.bat"  # [win]
    requirements:
      build:
        - cmake  # [win]
        - patch  # [win]
        - {{ compiler('fortran') }}        # [unix]
        - {{ compiler('m2w64_fortran') }}  # [win]
        - {{ compiler('c') }}        # [unix]
        - {{ compiler('m2w64_c') }}  # [win]
      host:
        - blas 1.1 {{ variant }}  # [not win]
        - openblas                  # [not win]
        - m2w64-openblas  # [win]
        - metis  # [not win]
        - scotch  # [not win]
      run:
        - {{ pin_subpackage('mumps-include', max_pin='x.x.x') }}  # [not win]
        - blas 1.1 {{ variant }}  # [not win]
        - openblas                  # [not win]
        - m2w64-openblas  # [win]
        - metis  # [not win]
        - scotch  # [not win]

    test:
      commands:
        {% if not win %}
        - test -f "${PREFIX}/lib/libsmumps_seq.a"
        - test -f "${PREFIX}/lib/libdmumps_seq.a"
        - test -f "${PREFIX}/lib/libcmumps_seq.a"
        - test -f "${PREFIX}/lib/libzmumps_seq.a"
        - test -f "${PREFIX}/lib/libmumps_common_seq.a"
        - test -f "${PREFIX}/lib/libpord_seq.a"
        - test -f "${PREFIX}/lib/libmpiseq.a"
        - test -f "${PREFIX}/include/mumps_seq/mpi.h"
        - test -f "${PREFIX}/include/mumps_seq/mpif.h"
        {% else %}
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libsmumps.dll" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libdmumps.dll" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libcmumps.dll" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libzmumps.dll" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\lib\libmumps_common.a" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\lib\libpord.a" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\include\dmumps_struc.h" exit 1
        {% endif %}

  {% else %}
  - name: mumps-mpi
    build:
      skip: true  # [win]
      script: ${RECIPE_DIR}/build-mpi.sh
      features:
        - blas_{{ variant }}  # [not win]
    requirements:
      build:
        - {{ compiler('fortran') }}  # [not win]
        - {{ compiler('c') }}  # [not win]
      host:
        - blas 1.1 {{ variant }}
        - openblas
        - {{ mpi }}
        - metis
        - parmetis
        - ptscotch
        - scalapack
      run:
        - {{ pin_subpackage('mumps-include', exact=True) }}
        - blas 1.1 {{ variant }}
        - openblas
        - {{ mpi }}
        - metis
        - parmetis
        - ptscotch
        - scalapack

    test:
      commands:
        - test -f "${PREFIX}/lib/libsmumps.a"
        - test -f "${PREFIX}/lib/libdmumps.a"
        - test -f "${PREFIX}/lib/libcmumps.a"
        - test -f "${PREFIX}/lib/libzmumps.a"
        - test -f "${PREFIX}/lib/libmumps_common.a"
        - test -f "${PREFIX}/lib/libpord.a"
        - test ! -f "${PREFIX}/lib/libmpiseq.a"
        - test ! -d "${PREFIX}/include/mumps_seq"
    {% endif %}

about:
  home: http://mumps.enseeiht.fr/
  license: CeCILL-C
  license_file: LICENSE
  summary: 'MUMPS: a parallel sparse direct solver'
  description: |
    MUMPS (MUltifrontal Massively Parallel Solver) is a package for solving
    systems of linear equations of the form Ax = b, where A is a square sparse
    matrix that can be either unsymmetric, symmetric positive definite, or
    general symmetric, on distributed memory computers. MUMPS implements a
    direct method based on a multifrontal approach which performs a Gaussian
    factorization.
  doc_url: http://mumps.enseeiht.fr/index.php?page=doc

extra:
  recipe-maintainers:
    - basnijholt
    - dalcinl
    - minrk
    - jbweston
