travis:
  secure:
    BINSTAR_TOKEN: wY0Dk26GFApB4p8Wa7KRTkWvxtvfRJY85o2b5cuSmGVAVCLMRi+X/Uh/BxizoZpCUeB+o1SUCe9a9kZWR//wTnvzusmQWb8DE5/MTwTLR7AlQLYMHaajqxnTqMX9DFnZjTeCUSbH2+e+HBDWn58tKxwmt1WSb5tBu6G4et1TmBNpW1f1pabr5VYDBvrZPsQXx2p2CgwekmD6UEAZy7u9/QxC/xujVjUVYTQvkFd1LRD6b1dHeHooTXHnZOEOvcidZEUStvCpnh0+9Y/qDWTx66jTU+32jK8TzZaerTusAff5x5CxyQyo1+HEaNZL/qQGFrxo8pFwod/tsuQpUF2nJ0X8+mwLDaYFysXXn5lSX+7nQQPqk2aoUJDLvNAsH28lgf+qpr7bhUX1Ewi/hCRmMKICSNrIMb0bJ3cBUeSlsnpPp92r1uszeHExMTWp9N+T2nAtU0GiqLjHoScDXn/guMOFwY9KdDFMMFTKNAJVC8Y6ZaE7mMCUNI5v6aast5DdSML/EjRdMqExUZJZ3oKUsym8nnBNlM9LD1YcA6Ea95nK0+hYJ67RVloBLZF6O9UBeJaYP851XuCrZljD1jIr+xtmuQVTtOSOFRfkdZ/AswCNbNzUwqOMDqVM0VAiimPDyRn17ogJPfuMlvjE8TXiV/kbDBlgztlfIi1jAk/mrWY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
