travis:
  secure:
    BINSTAR_TOKEN: ShEinTczBuBd3Hu6Fsy2CFQRnBIdNFzfGjnd56Um03WnMioNxMLVKpnL0nfF6qY4FHkNR8J/704cUc6fm19YqyjSYGwkkwHdf1EnWZeqXIePaIPOGbE8Igg4Zr6jjJBgupZHo/73x9KNZQsX5E91MBqydlvb+7aTE2fvFPP9q5MRQbnME/qAzbCUXLLWY+WoReZ7DKYx3UFoCI08Wul4KsGoNkwMV86/qfc9l4IjJJq79AQJLX8dHZk4zj42cx35ANoJk12baLjZCoZDuKbfyl8hdJRL2U4P7EtIQ/x4KZUptZlBuZLRKL2KIk763myr0N3wsQdaBDxLOyKWfPHZXi5F+bn5OBLHD9fM0giWobwtcXZcYTGbxOEzrPwi7I3+D5tHKKQ6sQP8AkXUyr4UPj/fkElUzB690omemAZjpqyLw9fTYyOEVn0ANP1hmLsn7Crt1yBqE8CieZAmYKoAWpSm/7Bhz4ajgh0PfH/FpGUbFv5jeO7foZAHbNW06GCWXbyfWvDhHwTJDSNsV7ayMjPfx8vf9sUz/BZsJhqp1ptFWzGIJr0QYeLAvn2zeD0oWIa9OwWQFnLo4W+rbDytAPWaBWC3WJ4z2/VgBh3gstLVHh3EAZazWQwfAQqNMwdD/PmouM/aPn4L23kmzZd0rYe2W+7+KgzBVWAFsoPID9A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
