travis:
  secure:
    BINSTAR_TOKEN: VHW9JRZiNpEUghrgOMbhcf83LGAKNo5T9eqkHd5Ketq52CrxQ7lN5XSQn0oSKGAIfQp3x//wF1ohKGyO66TNwty8Fcj3uHeAhXu3lM0yGg28IA7Yg4EBhYseolECI0Zxt9P8hCfmeQj0+3gQ7uInTa2B1IktAgoN2PrzXVJmsuWYkpEN8f8gKxWWz5pQUDawaW67M6SQmzVmGBMUDuM04akOY7cO6sg8v+H3EE9d4g2qwJ/pPoDttJX+rYIbH6i3EXnMzcBzGb8f9QJ5PS5kKSyJZA1hgrDnI48ucQJPb4fFV3UPe8+x7RJCWhzOER3VYtlZWKItp3n5l5j6zeRNT2yev7vsZ7TZXxtU7YLExssbVkUCgW7MitOAgQt5ykNUJbv3ngtThvlEcccUquNfODgRBYSIlnk1fMhKsC/R98KaOe1T54sy8JgB6NYanS4Tc21HcyvnxsO2Mn1yrZoGz5Fbz4n4oGj0aRDooVOzSypyN7gK2qWgMACY08NjbPe/iKmlD1gKXq/R5WvrxawtgfjB0XjlP/tf4WZnLJABa5DhVtGCsDkqb5Ur520IzGjax/tGFhlJuQGhVfM+ZX3fBAdR2gb7KZBL7kO0sgpNxqnt0s/5TJd65rAvN7gCVKdfU57N0EuFH3Y1TIWSTfDnkPhs6QYYxCoe4gwBrynsa3k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
